version: '3'

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
  
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links:
      - redis
  
  worker:
    build: .
    command: rq worker --with-scheduler --url redis://redis:6379
    depends_on:
      - redis
    links:
      - redis